
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build train container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-proj-group3-artifact/train-image',
    '--cache-from', 'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-proj-group3-artifact/train-image:latest',
    '-f',
    'dockerfiles/train.dockerfile'
  ]  
  secretEnv: ['WANDB_API_KEY']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push train container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-proj-group3-artifact/train-image'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build test container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-proj-group3-artifact/test-image',
    '-f',
    'dockerfiles/test.dockerfile'
  ]  
  secretEnv: ['WANDB_API_KEY']


- name: 'gcr.io/cloud-builders/docker'
  id: 'Push test container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-proj-group3-artifact/test-image'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/mlops-proj-group3-build-servic@dtumlops-448012.iam.gserviceaccount.com'


availableSecrets:
  secretManager:
  - versionName: "projects/$PROJECT_ID/secrets/WANDB_API_KEY/versions/latest"
    # secretEnv: "WANDB_API_KEY"
    env: "WANDB_API_KEY"

# Trigger image build with writing this in the terminal: gcloud builds submit --config=cloudbuild.yaml .   
# Authenticate access with service account: gcloud auth activate-service-account --key-file=cloud/dtumlops-448012-f2134e26466c.json 

