
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-proj-group3-artifact/train-image',
    '-f',
    'dockerfiles/train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-proj-group3-artifact/train-image'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/mlops-proj-group3-build-servic@dtumlops-448012.iam.gserviceaccount.com'
secretEnv: ['WANDB_API_KEY']

availableSecrets:
  secretManager:
  - versionName: "projects/$PROJECT_ID/secrets/WANDB_API_KEY/versions/latest"
    env: "WANDB_API_KEY"

# trigger image build with writing this in the terminal: gcloud builds submit --config=cloudbuild.yaml .
# Authenticate access with service account: gcloud auth activate-service-account --key-file=cloud/dtumlops-448012-f2134e26466c.json 