program: src/wikipedia/train.py
entity: mlops2025
project: wiki_classification
method: bayes 
metric:
    goal: maximize
    name: val_acc 
parameters:
    learning-rate:
        min: 0.001
        max: 0.05
        distribution: log_uniform_values
    optimizer-name:
      values: ['Adam', 'AdamW', 'NAdam', 'RMSprop']
    num-epochs:
        values: [300]
    weight-decay:
        values: [0.0001]
    dropout:
        min: 0.0
        max: 0.4
        distribution: uniform
    hidden-layers:
        min: 2
        max: 12
        distribution: int_uniform
    hidden-channels:
        min: 8
        max: 128
        distribution: int_uniform
    batch-size:
        values: [11701]
run_cap: 30
