program: src/wikipedia/train.py
entity: mlops2025
project: wiki_classification
method: bayes 
metric:
    goal: maximize
    name: val_acc 
parameters:
    learning-rate:
        min: 0.001
        max: 0.05
        distribution: log_uniform_values
    optimizer-name:
      values: ['Adam', 'AdamW', 'NAdam', 'RMSprop']
    num-epochs:
        values: [300]
    weight-decay:
        values: [0.0001]
    dropout:
        values: [0, 0.1]
    hidden-layers:
        values: [2, 4, 10]
    hidden-channels:
        values: [8, 16, 32]
    batch-size:
        values: [11701]
run_cap: 10
