program: src/wikipedia/train.py
entity: mlops2025
project: wiki_classification
method: bayes 
metric:
    goal: maximize
    name: val_acc 
parameters:
    learning-rate:
        min: 0.00001
        max: 0.01
        distribution: log_uniform_values
    optimizer-name:
        values: ['Adam', 'AdamW', 'NAdam', 'RMSprop']
    num-epochs:
        values: [50]
    num-splits:
        values: [1]
    weight-decay:
        min: 0.0001
        max: 0.01
        distribution: log_uniform_values
    dropout:
        min: 0.0
        max: 0.4
        distribution: uniform
    hidden-layers:
        min: 1
        max: 8
        distribution: int_uniform
    hidden-channels:
        min: 8
        max: 256
        distribution: int_uniform
    batch-size:
        values: [11701]
run_cap: 40