name: Unit Tests

on:
  push:
    branches:
      - main
      - actions
  pull_request:
    branches:
      - main

# Github secrets
# - uses: iterative/setup-dvc@v1
# - name: Get data
#   run: dvc pull
#   env:
#     GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
  
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "macos-latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install the project
        run: uv sync --all-extras --dev

      # **Authenticate with Google Cloud**
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: dtumlops-448012
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      
      # pip install gcloud
      - name: Install gcloud
        run: |
          curl -sSL https://sdk.cloud.google.com | bash > /dev/null
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} --quiet

      # **Set Google Cloud Project**
      - name: Set Google Cloud Project
        run: gcloud config set project dtumlops-448012


      - name: Run tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: uv run pytest tests

      - name: Enable caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Check data statistics
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: uv run src/wikipedia/dataset_statistics.py

      - name: Coverage report
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: uv run coverage report